#timer5959.xdc
# clock
set_property PACKAGE_PIN W5 [get_ports {clk}]
    set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
# active low reset
set_property PACKAGE_PIN V17 [get_ports {reset}]
    set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
# DIP switch
set_property PACKAGE_PIN R2 [get_ports {speedup}]        
    set_property IOSTANDARD LVCMOS33 [get_ports {speedup}]
set_property PACKAGE_PIN T1 [get_ports {setting}]        
    set_property IOSTANDARD LVCMOS33 [get_ports {setting}]
#push button
set_property PACKAGE_PIN U18 [get_ports {stop_in}]        
    set_property IOSTANDARD LVCMOS33 [get_ports {stop_in}]
set_property PACKAGE_PIN U17 [get_ports {pause_in}]
    set_property IOSTANDARD LVCMOS33 [get_ports {pause_in}]
set_property PACKAGE_PIN W19 [get_ports {set_min_in}]        
    set_property IOSTANDARD LVCMOS33 [get_ports {set_min_in}]
set_property PACKAGE_PIN T17 [get_ports {set_sec_in}]
    set_property IOSTANDARD LVCMOS33 [get_ports {set_sec_in}]

#8 common segment controls
set_property PACKAGE_PIN W7 [get_ports {segs[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segs[7]}]
set_property PACKAGE_PIN W6 [get_ports {segs[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segs[6]}]
set_property PACKAGE_PIN U8 [get_ports {segs[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segs[5]}]
set_property PACKAGE_PIN V8 [get_ports {segs[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segs[4]}]
set_property PACKAGE_PIN U5 [get_ports {segs[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segs[3]}]
set_property PACKAGE_PIN V5 [get_ports {segs[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segs[2]}]
set_property PACKAGE_PIN U7 [get_ports {segs[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segs[1]}]
set_property PACKAGE_PIN V7 [get_ports {segs[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segs[0]}]
# Four anode control signals
set_property PACKAGE_PIN W4 [get_ports {ssd_ctl[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[3]}]
set_property PACKAGE_PIN V4 [get_ports {ssd_ctl[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[2]}]
set_property PACKAGE_PIN U4 [get_ports {ssd_ctl[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[1]}]
set_property PACKAGE_PIN U2 [get_ports {ssd_ctl[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[0]}]
# pb check led
set_property PACKAGE_PIN L1 [get_ports {stop}]
    set_property IOSTANDARD LVCMOS33 [get_ports {stop}]
set_property PACKAGE_PIN P1 [get_ports {pause}]
    set_property IOSTANDARD LVCMOS33 [get_ports {pause}]
set_property PACKAGE_PIN N3 [get_ports {set_min}]        
    set_property IOSTANDARD LVCMOS33 [get_ports {set_min}]
set_property PACKAGE_PIN P3 [get_ports {set_sec}]
    set_property IOSTANDARD LVCMOS33 [get_ports {set_sec}]
#all leds
#set_property PACKAGE_PIN L1 [get_ports {leds[15]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {leds[15]}]
#set_property PACKAGE_PIN P1 [get_ports {leds[14]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {leds[14]}]
#set_property PACKAGE_PIN N3 [get_ports {leds[13]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {leds[13]}]
#set_property PACKAGE_PIN P3 [get_ports {leds[12]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {leds[12]}]

set_property PACKAGE_PIN U3 [get_ports {leds[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[11]}]
set_property PACKAGE_PIN W3 [get_ports {leds[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[10]}]
set_property PACKAGE_PIN V3 [get_ports {leds[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[9]}]
set_property PACKAGE_PIN V13 [get_ports {leds[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[8]}]
set_property PACKAGE_PIN V14 [get_ports {leds[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property PACKAGE_PIN U14 [get_ports {leds[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property PACKAGE_PIN U15 [get_ports {leds[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property PACKAGE_PIN W18 [get_ports {leds[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property PACKAGE_PIN V19 [get_ports {leds[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]