# Clock 
set_property PACKAGE_PIN W5 [get_ports {clk}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {clk}] 
    create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
# active low reset 
set_property PACKAGE_PIN V17 [get_ports {rst_n}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}] 
# DIP switch
set_property PACKAGE_PIN R2 [get_ports {slow}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {slow}] 
set_property PACKAGE_PIN V16 [get_ports {power}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {power}] 
set_property PACKAGE_PIN W16 [get_ports {rod_3}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {rod_3}] 
set_property PACKAGE_PIN W17 [get_ports {rod_2}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {rod_2}] 
set_property PACKAGE_PIN W15 [get_ports {rod_1}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {rod_1}] 
set_property PACKAGE_PIN V15 [get_ports {rod_0}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {rod_0}] 
#push button
set_property PACKAGE_PIN T18 [get_ports {volume_up}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {volume_up}]
set_property PACKAGE_PIN U17 [get_ports {volume_dw}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {volume_dw}] 
# Pmod I2S 
set_property PACKAGE_PIN A14 [get_ports {audio_mclk}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {audio_mclk}] 
set_property PACKAGE_PIN A16 [get_ports {audio_lrck}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {audio_lrck}] 
set_property PACKAGE_PIN B15 [get_ports {audio_sck}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {audio_sck}] 
set_property PACKAGE_PIN B16 [get_ports {audio_sdin}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {audio_sdin}]
# Four anode control signals
set_property PACKAGE_PIN W4 [get_ports {ssd_ctl[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[3]}]
set_property PACKAGE_PIN V4 [get_ports {ssd_ctl[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[2]}]
set_property PACKAGE_PIN U4 [get_ports {ssd_ctl[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[1]}]
set_property PACKAGE_PIN U2 [get_ports {ssd_ctl[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[0]}]
#8 common segment controls
 set_property PACKAGE_PIN W7 [get_ports {segs[7]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {segs[7]}]
 set_property PACKAGE_PIN W6 [get_ports {segs[6]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {segs[6]}]
 set_property PACKAGE_PIN U8 [get_ports {segs[5]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {segs[5]}]
 set_property PACKAGE_PIN V8 [get_ports {segs[4]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {segs[4]}]
 set_property PACKAGE_PIN U5 [get_ports {segs[3]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {segs[3]}]
 set_property PACKAGE_PIN V5 [get_ports {segs[2]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {segs[2]}]
 set_property PACKAGE_PIN U7 [get_ports {segs[1]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {segs[1]}]
 set_property PACKAGE_PIN V7 [get_ports {segs[0]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {segs[0]}]
 #LEDs
 set_property PACKAGE_PIN L1 [get_ports {leds[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[15]}]
 set_property PACKAGE_PIN P1 [get_ports {leds[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[14]}]
 set_property PACKAGE_PIN N3 [get_ports {leds[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[13]}]
 set_property PACKAGE_PIN P3 [get_ports {leds[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[12]}]
 set_property PACKAGE_PIN U3 [get_ports {leds[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[11]}]
 set_property PACKAGE_PIN W3 [get_ports {leds[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[10]}]
 set_property PACKAGE_PIN V3 [get_ports {leds[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[9]}]
 set_property PACKAGE_PIN V13 [get_ports {leds[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[8]}]
 set_property PACKAGE_PIN V14 [get_ports {leds[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
 set_property PACKAGE_PIN U14 [get_ports {leds[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
 set_property PACKAGE_PIN U15 [get_ports {leds[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
 set_property PACKAGE_PIN W18 [get_ports {leds[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
 set_property PACKAGE_PIN V19 [get_ports {leds[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
 set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
 set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
 set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]

##VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vgaRed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN H19 [get_ports {vgaRed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
set_property PACKAGE_PIN J19 [get_ports {vgaRed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
set_property PACKAGE_PIN N19 [get_ports {vgaRed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
set_property PACKAGE_PIN N18 [get_ports {vgaBlue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[0]}]
set_property PACKAGE_PIN L18 [get_ports {vgaBlue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[1]}]
set_property PACKAGE_PIN K18 [get_ports {vgaBlue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[2]}]
set_property PACKAGE_PIN J18 [get_ports {vgaBlue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[3]}]
set_property PACKAGE_PIN J17 [get_ports {vgaGreen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[0]}]
set_property PACKAGE_PIN H17 [get_ports {vgaGreen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[1]}]
set_property PACKAGE_PIN G17 [get_ports {vgaGreen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[2]}]
set_property PACKAGE_PIN D17 [get_ports {vgaGreen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[3]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]