set_property IOSTANDARD LVCMOS33 [get_ports pb_left]
set_property IOSTANDARD LVCMOS33 [get_ports pb_center]
set_property IOSTANDARD LVCMOS33 [get_ports pb_right]
set_property IOSTANDARD LVCMOS33 [get_ports pb_up]
set_property IOSTANDARD LVCMOS33 [get_ports pb_down]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports fcrystal]
set_property IOSTANDARD LVCMOS33 [get_ports chord_switch]

set_property PACKAGE_PIN W19 [get_ports pb_left]
set_property PACKAGE_PIN U18 [get_ports pb_center]
set_property PACKAGE_PIN T17 [get_ports pb_right]
set_property PACKAGE_PIN T18 [get_ports pb_up]
set_property PACKAGE_PIN U17 [get_ports pb_down]
set_property PACKAGE_PIN V17 [get_ports rst_n]
set_property PACKAGE_PIN W5 [get_ports fcrystal]
set_property PACKAGE_PIN R2 [get_ports chord_switch]

# Speaker
set_property PACKAGE_PIN A14 [get_ports {audio_mclk}] 
set_property IOSTANDARD LVCMOS33 [get_ports {audio_mclk}] 
set_property PACKAGE_PIN A16 [get_ports {audio_lrck}] 
set_property IOSTANDARD LVCMOS33 [get_ports {audio_lrck}] 
set_property PACKAGE_PIN B15 [get_ports {audio_sck}] 
set_property IOSTANDARD LVCMOS33 [get_ports {audio_sck}] 
set_property PACKAGE_PIN B16 [get_ports {audio_din}] 
set_property IOSTANDARD LVCMOS33 [get_ports {audio_din}]