#tens digit secret input
set_property PACKAGE_PIN R2 [get_ports {sec_ten[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sec_ten[3]}]
set_property PACKAGE_PIN T1 [get_ports {sec_ten[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sec_ten[2]}]
set_property PACKAGE_PIN U1 [get_ports {sec_ten[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sec_ten[1]}]
set_property PACKAGE_PIN W2 [get_ports {sec_ten[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sec_ten[0]}]
#ones digit secret input
set_property PACKAGE_PIN R3 [get_ports {sec_one[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sec_one[3]}]
set_property PACKAGE_PIN T2 [get_ports {sec_one[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sec_one[2]}]
set_property PACKAGE_PIN T3 [get_ports {sec_one[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sec_one[1]}]
set_property PACKAGE_PIN V2 [get_ports {sec_one[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sec_one[0]}]
#tens digit guess input
set_property PACKAGE_PIN W13 [get_ports {gue_ten[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gue_ten[3]}]
set_property PACKAGE_PIN W14 [get_ports {gue_ten[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gue_ten[2]}]
set_property PACKAGE_PIN V15 [get_ports {gue_ten[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gue_ten[1]}]
set_property PACKAGE_PIN W15 [get_ports {gue_ten[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gue_ten[0]}]
#ones digit guess input
set_property PACKAGE_PIN W17 [get_ports {gue_one[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gue_one[3]}]
set_property PACKAGE_PIN W16 [get_ports {gue_one[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gue_one[2]}]
set_property PACKAGE_PIN V16 [get_ports {gue_one[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gue_one[1]}]
set_property PACKAGE_PIN V17 [get_ports {gue_one[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gue_one[0]}]

#3-bits bulls output
set_property PACKAGE_PIN L1 [get_ports {bulls[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {bulls[2]}]
set_property PACKAGE_PIN P1 [get_ports {bulls[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {bulls[1]}]
set_property PACKAGE_PIN N3 [get_ports {bulls[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {bulls[0]}]
#3-bits cows output
set_property PACKAGE_PIN U19 [get_ports {cows[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cows[2]}]
set_property PACKAGE_PIN E19 [get_ports {cows[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cows[1]}]
set_property PACKAGE_PIN U16 [get_ports {cows[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cows[0]}]